// Starting question bank for the Daily Quiz. Loaded with `npm run db:quiz` (skips questions already there).
// Each entry: [category, difficulty 1-3, question, right answer, wrong, wrong, wrong].
// Each day's quiz takes its questions from different categories (lib/quiz.ts), so keep categories few and broad.
// Players see the four answers shuffled. Avoid facts that change (who holds an office now, current records).

export const QUIZ_BANK = [
  // NYSC
  ["NYSC", 1, "What does NYSC stand for?", "National Youth Service Corps", "National Youth Service Council", "Nigerian Youth Service Corps", "National Youth Skills Corps"],
  ["NYSC", 1, "In which year was the NYSC established?", "1973", "1960", "1979", "1985"],
  ["NYSC", 2, "Which head of state established the NYSC?", "Yakubu Gowon", "Olusegun Obasanjo", "Murtala Mohammed", "Shehu Shagari"],
  ["NYSC", 1, "How long is the NYSC service year?", "One year", "Six months", "Eighteen months", "Two years"],
  ["NYSC", 1, "About how long does NYSC orientation camp last?", "Three weeks", "One week", "Six weeks", "Three months"],
  ["NYSC", 1, "What does CDS stand for in NYSC?", "Community Development Service", "Corps Duty Schedule", "Central Development Scheme", "Community Duty Session"],
  ["NYSC", 1, "What does PPA stand for in NYSC?", "Place of Primary Assignment", "Primary Posting Area", "Place of Public Appointment", "Posting and Placement Allocation"],
  ["NYSC", 2, "What does SAED stand for in NYSC?", "Skill Acquisition and Entrepreneurship Development", "Skills And Employment Drive", "Service And Enterprise Development", "Skill Advancement and Education Department"],
  ["NYSC", 1, "What is the NYSC motto?", "Service and Humility", "Unity and Faith", "Peace and Progress", "Service to the Nation"],
  ["NYSC", 1, "What do corpers call the monthly NYSC allowance?", "Allawee", "Kpanlogo", "Owo-camp", "Corper bonus"],
  ["NYSC", 2, "Graduates above what age are exempted from NYSC?", "30", "25", "28", "35"],
  ["NYSC", 2, "What certificate does a corper get after completing service?", "Certificate of National Service", "Certificate of Exemption", "Discharge Certificate", "Letter of Completion"],
  ["NYSC", 2, "Graduates who are too old to serve receive which certificate?", "Certificate of Exemption", "Certificate of National Service", "Waiver Letter", "Certificate of Excusal"],
  ["NYSC", 1, "What is the famous NYSC camp obstacle course called?", "Man O' War", "Iron Man", "Rough Rider", "Commando Drill"],
  ["NYSC", 1, "What is the market inside an NYSC orientation camp called?", "Mammy Market", "Corper Market", "Camp Bazaar", "Oja Corper"],
  ["NYSC", 2, "Who is the head of the NYSC scheme?", "The Director-General", "The Commandant-General", "The Chief Coordinator", "The Inspector-General"],
  ["NYSC", 2, "Who heads NYSC in each state?", "The State Coordinator", "The State Commandant", "The State Director", "The Camp Governor"],
  ["NYSC", 1, "What ceremony in camp makes you officially a corps member?", "Swearing-in", "Passing out", "Matriculation", "Induction parade"],
  ["NYSC", 1, "Which boots are part of the NYSC kit?", "Jungle boots", "Chelsea boots", "Desert boots", "Rain boots"],
  ["NYSC", 2, "NYSC was created by Decree No. ___ of 1973.", "24", "1", "12", "51"],
  ["NYSC", 1, "Which colour is the NYSC uniform?", "Khaki", "Navy blue", "Olive green", "Grey"],
  ["NYSC", 2, "What do corpers do on their CDS day?", "Community development work", "Military drills", "Camp exams", "Sports competitions"],
  ["NYSC", 2, "At the end of service, the closing event is called what?", "Passing out", "Swearing-in", "Graduation parade", "Final drill"],
  ["NYSC", 2, "Which official supervises corpers at the local government level?", "Local Government Inspector", "Local Corps Marshal", "Ward Coordinator", "LGA Commandant"],

  // Nigeria: history and civics
  ["Nigeria", 1, "When did Nigeria gain independence?", "1 October 1960", "1 October 1963", "12 June 1960", "29 May 1960"],
  ["Nigeria", 2, "In which year did Nigeria become a republic?", "1963", "1960", "1966", "1979"],
  ["Nigeria", 1, "Who was Nigeria's first Prime Minister?", "Abubakar Tafawa Balewa", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello"],
  ["Nigeria", 1, "Who was Nigeria's first President?", "Nnamdi Azikiwe", "Abubakar Tafawa Balewa", "Yakubu Gowon", "Shehu Shagari"],
  ["Nigeria", 2, "In which year did Abuja officially replace Lagos as Nigeria's capital?", "1991", "1976", "1985", "1999"],
  ["Nigeria", 1, "How many states does Nigeria have?", "36", "30", "37", "38"],
  ["Nigeria", 2, "How many local government areas does Nigeria have?", "774", "536", "650", "812"],
  ["Nigeria", 2, "In which year were Northern and Southern Nigeria amalgamated?", "1914", "1900", "1922", "1945"],
  ["Nigeria", 2, "Who amalgamated Northern and Southern Nigeria?", "Lord Frederick Lugard", "Sir Arthur Richards", "Sir John Macpherson", "Sir James Robertson"],
  ["Nigeria", 2, "Who suggested the name \"Nigeria\"?", "Flora Shaw", "Mary Slessor", "Lord Lugard", "Queen Elizabeth II"],
  ["Nigeria", 1, "What are the colours of the Nigerian flag?", "Green, white, green", "Green, white, red", "Green, yellow, green", "White, green, white"],
  ["Nigeria", 2, "Who designed the Nigerian flag?", "Taiwo Akinkunmi", "Ben Enwonwu", "Herbert Macaulay", "Pa Benedict Odiase"],
  ["Nigeria", 1, "Which years did the Nigerian Civil War last?", "1967 to 1970", "1960 to 1963", "1966 to 1968", "1970 to 1975"],
  ["Nigeria", 2, "In 2024 Nigeria brought back which national anthem?", "Nigeria, We Hail Thee", "Arise, O Compatriots", "Nigeria, Our Land", "Rise, Nigeria"],
  ["Nigeria", 2, "On the coat of arms, what does the Y shape stand for?", "The Niger and Benue rivers", "Unity and faith", "The north and the south", "Peace and progress"],
  ["Nigeria", 2, "What colour is the eagle on Nigeria's coat of arms?", "Red", "Black", "Gold", "Green"],
  ["Nigeria", 1, "What is Nigeria's currency?", "Naira", "Cedi", "Shilling", "Rand"],
  ["Nigeria", 2, "In which year was the naira introduced?", "1973", "1960", "1965", "1980"],
  ["Nigeria", 1, "How many kobo make one naira?", "100", "10", "50", "1,000"],
  ["Nigeria", 1, "Which is Nigeria's largest city by population?", "Lagos", "Kano", "Ibadan", "Abuja"],
  ["Nigeria", 1, "Which is the longest river in Nigeria?", "River Niger", "River Benue", "River Kaduna", "Cross River"],
  ["Nigeria", 2, "Where do the Niger and Benue rivers meet?", "Lokoja", "Onitsha", "Makurdi", "Jebba"],
  ["Nigeria", 3, "What is the highest point in Nigeria?", "Chappal Waddi", "Zuma Rock", "Obudu Plateau", "Shere Hills"],
  ["Nigeria", 2, "How many geopolitical zones does Nigeria have?", "6", "4", "5", "8"],
  ["Nigeria", 2, "Where was oil first found in commercial quantity in Nigeria?", "Oloibiri", "Bonny", "Warri", "Escravos"],
  ["Nigeria", 3, "In which year was oil first found in commercial quantity in Nigeria?", "1956", "1948", "1960", "1971"],
  ["Nigeria", 3, "In which year did Nigeria join OPEC?", "1971", "1960", "1965", "1980"],
  ["Nigeria", 2, "Where is the headquarters of ECOWAS?", "Abuja", "Accra", "Lagos", "Dakar"],
  ["Nigeria", 1, "How many senators are in the Nigerian Senate?", "109", "36", "100", "360"],
  ["Nigeria", 2, "How many members are in the House of Representatives?", "360", "109", "250", "469"],
  ["Nigeria", 1, "How long is a Nigerian president's term?", "4 years", "5 years", "6 years", "7 years"],
  ["Nigeria", 1, "Which of these countries does NOT border Nigeria?", "Ghana", "Benin", "Cameroon", "Chad"],
  ["Nigeria", 1, "Which rock in Abuja is home to the seat of the Federal Government?", "Aso Rock", "Zuma Rock", "Olumo Rock", "Idanre Hills"],
  ["Nigeria", 1, "What is Nigeria often called?", "The Giant of Africa", "The Pearl of Africa", "The Rainbow Nation", "The Heart of Africa"],
  ["Nigeria", 2, "Which two cities does the Second Niger Bridge connect?", "Asaba and Onitsha", "Lokoja and Ajaokuta", "Calabar and Uyo", "Makurdi and Lafia"],
  ["Nigeria", 2, "Who is called the father of Nigerian nationalism?", "Herbert Macaulay", "Nnamdi Azikiwe", "Obafemi Awolowo", "Anthony Enahoro"],
  ["Nigeria", 2, "Who founded the Sokoto Caliphate?", "Usman dan Fodio", "Ahmadu Bello", "Muhammadu Bello", "Abubakar Atiku"],
  ["Nigeria", 2, "Queen Amina was a warrior queen of which kingdom?", "Zazzau (Zaria)", "Kano", "Oyo", "Benin"],
  ["Nigeria", 2, "The Benin Bronzes come from which kingdom?", "Benin Kingdom", "Oyo Empire", "Kanem-Bornu", "Nri Kingdom"],
  ["Nigeria", 3, "The ancient Nok culture is best known for what?", "Terracotta sculptures", "Bronze heads", "Stone monoliths", "Ivory masks"],
  ["Nigeria", 2, "Moremi Ajasoro is a heroine of which town?", "Ile-Ife", "Oyo", "Abeokuta", "Ibadan"],
  ["Nigeria", 2, "Funmilayo Ransome-Kuti led the famous women's protest in which town?", "Abeokuta", "Aba", "Lagos", "Ibadan"],
  ["Nigeria", 3, "The 1929 women's protest against colonial taxes is known as what?", "The Aba Women's Riot", "The Egba Uprising", "The Iva Valley Protest", "The Ekumeku Movement"],
  ["Nigeria", 2, "Which Nigerian won the Nobel Prize in Literature?", "Wole Soyinka", "Chinua Achebe", "Ben Okri", "Chimamanda Ngozi Adichie"],
  ["Nigeria", 2, "In which year did Wole Soyinka win the Nobel Prize?", "1986", "1976", "1993", "2001"],
  ["Nigeria", 2, "Which agency conducts elections in Nigeria?", "INEC", "NIMC", "EFCC", "NCC"],
  ["Nigeria", 3, "Which was Nigeria's first university?", "University of Ibadan", "University of Nigeria, Nsukka", "University of Lagos", "Ahmadu Bello University"],
  ["Nigeria", 3, "In which year was University College Ibadan founded?", "1948", "1960", "1932", "1955"],
  ["Nigeria", 2, "Ahmadu Bello University is in which city?", "Zaria", "Kaduna", "Kano", "Sokoto"],
  ["Nigeria", 2, "Obafemi Awolowo University is in which town?", "Ile-Ife", "Ibadan", "Osogbo", "Akure"],
  ["Nigeria", 2, "The University of Nigeria is in which town?", "Nsukka", "Enugu", "Awka", "Owerri"],
  ["Nigeria", 1, "Which country is Nigeria's big jollof rival?", "Ghana", "Senegal", "Cameroon", "Togo"],
  ["Nigeria", 1, "Which bridge is the longest in Lagos?", "Third Mainland Bridge", "Carter Bridge", "Eko Bridge", "Lekki-Ikoyi Link Bridge"],
  ["Nigeria", 2, "Which Lagos airport is the main international airport?", "Murtala Muhammed International Airport", "Nnamdi Azikiwe International Airport", "Mallam Aminu Kano International Airport", "Port Harcourt International Airport"],
  ["Nigeria", 2, "The Nnamdi Azikiwe International Airport is in which city?", "Abuja", "Lagos", "Enugu", "Onitsha"],
  ["Nigeria", 2, "Where is the Dangote Refinery?", "Lekki, Lagos", "Port Harcourt", "Warri", "Kaduna"],
  ["Nigeria", 2, "Kainji Dam is on which river?", "River Niger", "River Benue", "River Kaduna", "River Ogun"],
  ["Nigeria", 1, "What are Nigeria's three largest ethnic groups?", "Hausa, Yoruba and Igbo", "Hausa, Ijaw and Tiv", "Yoruba, Igbo and Efik", "Fulani, Kanuri and Nupe"],
  ["Nigeria", 2, "Ngozi Okonjo-Iweala became Director-General of which organisation in 2021?", "World Trade Organization", "World Bank", "United Nations", "African Union"],

  // Nigeria: states
  ["Nigeria", 1, "What is the capital of Akwa Ibom State?", "Uyo", "Calabar", "Eket", "Ikot Ekpene"],
  ["Nigeria", 1, "What is the capital of Bayelsa State?", "Yenagoa", "Brass", "Port Harcourt", "Ogbia"],
  ["Nigeria", 1, "What is the capital of Ebonyi State?", "Abakaliki", "Afikpo", "Enugu", "Onueke"],
  ["Nigeria", 2, "What is the capital of Nasarawa State?", "Lafia", "Keffi", "Akwanga", "Nasarawa"],
  ["Nigeria", 2, "What is the capital of Zamfara State?", "Gusau", "Kaura Namoda", "Talata Mafara", "Anka"],
  ["Nigeria", 2, "What is the capital of Jigawa State?", "Dutse", "Hadejia", "Kazaure", "Gumel"],
  ["Nigeria", 2, "What is the capital of Yobe State?", "Damaturu", "Potiskum", "Gashua", "Nguru"],
  ["Nigeria", 2, "What is the capital of Taraba State?", "Jalingo", "Wukari", "Yola", "Bali"],
  ["Nigeria", 1, "What is the capital of Kogi State?", "Lokoja", "Okene", "Idah", "Kabba"],
  ["Nigeria", 1, "What is the capital of Kwara State?", "Ilorin", "Offa", "Omu-Aran", "Jebba"],
  ["Nigeria", 1, "What is the capital of Ekiti State?", "Ado-Ekiti", "Ikere-Ekiti", "Akure", "Ijero-Ekiti"],
  ["Nigeria", 1, "What is the capital of Ondo State?", "Akure", "Ondo", "Owo", "Ado-Ekiti"],
  ["Nigeria", 1, "What is the capital of Osun State?", "Osogbo", "Ile-Ife", "Ilesa", "Ede"],
  ["Nigeria", 1, "What is the capital of Delta State?", "Asaba", "Warri", "Sapele", "Ughelli"],
  ["Nigeria", 1, "What is the capital of Imo State?", "Owerri", "Orlu", "Okigwe", "Umuahia"],
  ["Nigeria", 1, "What is the capital of Abia State?", "Umuahia", "Aba", "Owerri", "Ohafia"],
  ["Nigeria", 1, "What is the capital of Anambra State?", "Awka", "Onitsha", "Nnewi", "Enugu"],
  ["Nigeria", 1, "What is the capital of Cross River State?", "Calabar", "Uyo", "Ikom", "Ogoja"],
  ["Nigeria", 1, "What is the capital of Benue State?", "Makurdi", "Gboko", "Otukpo", "Lafia"],
  ["Nigeria", 1, "What is the capital of Plateau State?", "Jos", "Bukuru", "Pankshin", "Shendam"],
  ["Nigeria", 1, "What is the capital of Adamawa State?", "Yola", "Mubi", "Jalingo", "Numan"],
  ["Nigeria", 1, "What is the capital of Niger State?", "Minna", "Bida", "Suleja", "Kontagora"],
  ["Nigeria", 1, "What is the capital of Borno State?", "Maiduguri", "Bama", "Biu", "Damaturu"],
  ["Nigeria", 1, "What is the capital of Edo State?", "Benin City", "Auchi", "Ekpoma", "Asaba"],
  ["Nigeria", 1, "What is the capital of Rivers State?", "Port Harcourt", "Bonny", "Yenagoa", "Ahoada"],
  ["Nigeria", 1, "What is the capital of Ogun State?", "Abeokuta", "Ijebu-Ode", "Sagamu", "Ota"],
  ["Nigeria", 1, "What is the capital of Oyo State?", "Ibadan", "Oyo", "Ogbomoso", "Iseyin"],
  ["Nigeria", 1, "What is the capital of Lagos State?", "Ikeja", "Lagos Island", "Victoria Island", "Epe"],
  ["Nigeria", 2, "What is the capital of Kebbi State?", "Birnin Kebbi", "Argungu", "Jega", "Yauri"],
  ["Nigeria", 1, "What is the capital of Katsina State?", "Katsina", "Funtua", "Daura", "Malumfashi"],
  ["Nigeria", 1, "What is the capital of Gombe State?", "Gombe", "Kaltungo", "Dukku", "Billiri"],
  ["Nigeria", 1, "Which state is called the \"Centre of Excellence\"?", "Lagos", "Oyo", "Kano", "Rivers"],
  ["Nigeria", 1, "Which state is called the \"Gateway State\"?", "Ogun", "Lagos", "Kwara", "Kogi"],
  ["Nigeria", 1, "Which state is called the \"Coal City State\"?", "Enugu", "Kogi", "Benue", "Ebonyi"],
  ["Nigeria", 1, "Which state is called the \"Land of Promise\"?", "Akwa Ibom", "Cross River", "Rivers", "Delta"],
  ["Nigeria", 2, "Which state is called the \"Glory of All Lands\"?", "Bayelsa", "Delta", "Rivers", "Edo"],
  ["Nigeria", 1, "Which state is called the \"Centre of Commerce\"?", "Kano", "Lagos", "Anambra", "Kaduna"],
  ["Nigeria", 2, "Which state is called the \"Home of Peace and Tourism\"?", "Plateau", "Cross River", "Bauchi", "Ekiti"],
  ["Nigeria", 2, "Which state is called the \"Pace Setter State\"?", "Oyo", "Ogun", "Lagos", "Ondo"],
  ["Nigeria", 2, "Which state is called the \"Fountain of Knowledge\"?", "Ekiti", "Oyo", "Osun", "Kwara"],
  ["Nigeria", 2, "Which state is called the \"Sunshine State\"?", "Ondo", "Ekiti", "Lagos", "Delta"],
  ["Nigeria", 2, "Which state is called the \"Light of the Nation\"?", "Anambra", "Enugu", "Imo", "Abia"],
  ["Nigeria", 1, "Which state is called \"God's Own State\"?", "Abia", "Imo", "Anambra", "Enugu"],
  ["Nigeria", 2, "Which state is called the \"Heartbeat of the Nation\"?", "Edo", "Kogi", "Kwara", "FCT"],
  ["Nigeria", 2, "Which state is called the \"Treasure Base of the Nation\"?", "Rivers", "Bayelsa", "Delta", "Akwa Ibom"],
  ["Nigeria", 1, "Which state is called the \"Confluence State\"?", "Kogi", "Niger", "Benue", "Kwara"],
  ["Nigeria", 2, "Which state is called the \"State of Harmony\"?", "Kwara", "Kogi", "Plateau", "Osun"],
  ["Nigeria", 2, "Which state is called the \"Power State\"?", "Niger", "Kogi", "Kaduna", "Kwara"],
  ["Nigeria", 3, "Which state is called the \"Home of Solid Minerals\"?", "Nasarawa", "Kogi", "Plateau", "Ebonyi"],
  ["Nigeria", 2, "Which state is called the \"Salt of the Nation\"?", "Ebonyi", "Enugu", "Cross River", "Abia"],
  ["Nigeria", 2, "Which state is called the \"Eastern Heartland\"?", "Imo", "Abia", "Enugu", "Anambra"],
  ["Nigeria", 2, "Which state is called the \"Seat of the Caliphate\"?", "Sokoto", "Kano", "Katsina", "Kebbi"],
  ["Nigeria", 3, "Which state is called the \"Jewel in the Savannah\"?", "Gombe", "Bauchi", "Adamawa", "Jigawa"],
  ["Nigeria", 2, "Which state is called \"The Big Heart\"?", "Delta", "Edo", "Rivers", "Lagos"],
  ["Nigeria", 3, "Which state is called \"Nature's Gift to the Nation\"?", "Taraba", "Cross River", "Plateau", "Adamawa"],
  ["Nigeria", 2, "Which state is called the \"State of the Living Spring\"?", "Osun", "Ekiti", "Ogun", "Oyo"],
  ["Nigeria", 2, "Which state is called the \"Centre of Learning\"?", "Kaduna", "Kano", "Oyo", "Enugu"],
  ["Nigeria", 1, "Zuma Rock is in which state?", "Niger", "FCT", "Kaduna", "Kogi"],
  ["Nigeria", 1, "Olumo Rock is in which city?", "Abeokuta", "Ibadan", "Akure", "Ilorin"],
  ["Nigeria", 1, "Yankari Game Reserve is in which state?", "Bauchi", "Gombe", "Plateau", "Taraba"],
  ["Nigeria", 1, "Obudu Mountain Resort is in which state?", "Cross River", "Plateau", "Taraba", "Akwa Ibom"],
  ["Nigeria", 2, "Erin Ijesha (Olumirin) Waterfalls are in which state?", "Osun", "Ekiti", "Ondo", "Kwara"],
  ["Nigeria", 2, "Ikogosi Warm Springs are in which state?", "Ekiti", "Ondo", "Osun", "Kogi"],
  ["Nigeria", 2, "The Osun-Osogbo Sacred Grove, a UNESCO site, is in which state?", "Osun", "Oyo", "Ogun", "Ekiti"],
  ["Nigeria", 3, "The Sukur Cultural Landscape, a UNESCO site, is in which state?", "Adamawa", "Borno", "Taraba", "Gombe"],
  ["Nigeria", 2, "Which of these states was created in 1996?", "Ekiti", "Lagos", "Kano", "Ogun"],
  ["Nigeria", 2, "Which of these South-South states was created in 1996?", "Bayelsa", "Rivers", "Delta", "Akwa Ibom"],
  ["Nigeria", 3, "Which of these North-West states was created in 1996?", "Zamfara", "Sokoto", "Kebbi", "Katsina"],
  ["Nigeria", 2, "Oil was first discovered in Oloibiri, in today's which state?", "Bayelsa", "Rivers", "Delta", "Akwa Ibom"],
  ["Nigeria", 2, "Chappal Waddi, Nigeria's highest point, is in which state?", "Taraba", "Adamawa", "Plateau", "Cross River"],
  ["Nigeria", 1, "Lokoja, where the Niger and Benue meet, is the capital of which state?", "Kogi", "Niger", "Kwara", "Benue"],
  ["Nigeria", 2, "Which state's capital is Ado-Ekiti?", "Ekiti", "Ondo", "Osun", "Kwara"],

  // Naija life, music and film
  ["Naija Life", 1, "Who wrote \"Things Fall Apart\"?", "Chinua Achebe", "Wole Soyinka", "Cyprian Ekwensi", "Buchi Emecheta"],
  ["Naija Life", 2, "In which year was \"Things Fall Apart\" published?", "1958", "1960", "1966", "1972"],
  ["Naija Life", 1, "Who wrote \"Half of a Yellow Sun\"?", "Chimamanda Ngozi Adichie", "Chinua Achebe", "Buchi Emecheta", "Sefi Atta"],
  ["Naija Life", 2, "Who wrote \"The Joys of Motherhood\"?", "Buchi Emecheta", "Flora Nwapa", "Chimamanda Ngozi Adichie", "Zaynab Alkali"],
  ["Naija Life", 3, "Who wrote the memoir \"Aké: The Years of Childhood\"?", "Wole Soyinka", "Chinua Achebe", "Ben Okri", "J.P. Clark"],
  ["Music", 1, "Fela Kuti pioneered which music genre?", "Afrobeat", "Highlife", "Fuji", "Juju"],
  ["Music", 2, "What was the name of Fela Kuti's famous Lagos club?", "The Afrika Shrine", "Kalakuta Club", "The Jazz Hole", "Freedom Park"],
  ["Music", 2, "Which Burna Boy album won a Grammy?", "Twice as Tall", "African Giant", "Love, Damini", "I Told Them..."],
  ["Music", 1, "What is Burna Boy's nickname?", "African Giant", "Starboy", "OBO", "Baddo"],
  ["Music", 1, "What is Wizkid's nickname?", "Starboy", "African Giant", "OBO", "Odogwu"],
  ["Music", 1, "Which artist is known as OBO?", "Davido", "Wizkid", "Burna Boy", "Olamide"],
  ["Music", 2, "Which Nigerian artist was on Beyoncé's \"Brown Skin Girl\"?", "Wizkid", "Burna Boy", "Davido", "Tiwa Savage"],
  ["Music", 2, "Which Nigerian singer is on Future's hit \"Wait for U\"?", "Tems", "Ayra Starr", "Tiwa Savage", "Yemi Alade"],
  ["Music", 1, "Rema's \"Calm Down\" remix featured which American singer?", "Selena Gomez", "Ariana Grande", "Rihanna", "Doja Cat"],
  ["Music", 2, "Which record label did Olamide found?", "YBNL", "Mavin Records", "Chocolate City", "DMW"],
  ["Music", 2, "Who founded Mavin Records?", "Don Jazzy", "Olamide", "D'banj", "Davido"],
  ["Music", 1, "Who sang \"African Queen\"?", "2Baba", "P-Square", "D'banj", "Timaya"],
  ["Music", 1, "What are the names of the P-Square twins?", "Peter and Paul", "Peter and Patrick", "Paul and Philip", "Patrick and Paul"],
  ["Movies & TV", 1, "What is Nigeria's film industry called?", "Nollywood", "Naijawood", "Lagoswood", "Afrowood"],
  ["Movies & TV", 2, "Which 1992 film is often called the start of Nollywood?", "Living in Bondage", "Glamour Girls", "Osuofia in London", "Rattlesnake"],
  ["Movies & TV", 2, "Who directed the 2016 hit film \"The Wedding Party\"?", "Kemi Adetiba", "Funke Akindele", "Kunle Afolayan", "Genevieve Nnaji"],
  ["Movies & TV", 1, "Which actress created and starred in \"Jenifa\"?", "Funke Akindele", "Mercy Johnson", "Omotola Jalade-Ekeinde", "Toyin Abraham"],
  ["Naija Life", 1, "Amala is usually made from what?", "Yam flour", "Cassava", "Rice", "Maize"],
  ["Naija Life", 1, "Eba is made from what?", "Garri", "Yam", "Plantain", "Rice"],
  ["Naija Life", 1, "Egusi soup is made from what?", "Melon seeds", "Groundnuts", "Okra", "Palm fruit"],
  ["Naija Life", 1, "Tuwo shinkafa is made from what?", "Rice", "Yam", "Millet", "Beans"],
  ["Naija Life", 1, "What is suya?", "Spicy grilled meat on sticks", "Fried bean cakes", "Steamed bean pudding", "Fried dough balls"],
  ["Naija Life", 2, "What is the spicy pepper mix on suya called?", "Yaji", "Iru", "Ogiri", "Uziza"],
  ["Naija Life", 1, "What is akara made from?", "Beans", "Yam", "Plantain", "Cassava"],
  ["Naija Life", 2, "Fura da nono is made from millet and what?", "Fermented milk", "Coconut milk", "Palm wine", "Zobo"],
  ["Naija Life", 2, "Banga soup is made from what?", "Palm fruit", "Melon seeds", "Groundnuts", "Okra"],
  ["Naija Life", 2, "Edikang Ikong soup comes from which people?", "Efik and Ibibio", "Tiv", "Ijaw", "Urhobo"],
  ["Naija Life", 2, "Ofe Onugbu is which soup?", "Bitterleaf soup", "Okra soup", "Pepper soup", "Oha soup"],
  ["Naija Life", 2, "Ofada rice is usually eaten with which stew?", "Ayamase", "Banga", "Egusi", "Miyan kuka"],
  ["Naija Life", 1, "Zobo drink is made from what?", "Hibiscus leaves", "Ginger only", "Tiger nuts", "Palm sap"],
  ["Naija Life", 2, "Kunu is a drink usually made from what?", "Millet or sorghum", "Hibiscus", "Palm sap", "Cashew"],
  ["Naija Life", 2, "The Argungu Fishing Festival happens in which state?", "Kebbi", "Sokoto", "Niger", "Kwara"],
  ["Naija Life", 1, "The Eyo Festival is held in which city?", "Lagos", "Ibadan", "Benin City", "Calabar"],
  ["Naija Life", 1, "The Calabar Carnival happens in which state?", "Cross River", "Akwa Ibom", "Rivers", "Lagos"],
  ["Naija Life", 2, "The Ojude Oba festival is held in which town?", "Ijebu-Ode", "Abeokuta", "Oyo", "Ilorin"],
  ["Naija Life", 2, "The Durbar festival is famous for what?", "Horse riders in colourful regalia", "Masquerades on stilts", "Canoe racing", "Wrestling"],
  ["Naija Life", 2, "The New Yam Festival is called what in Igbo?", "Iri Ji", "Ofala", "Mmanwu", "Igu Aro"],
  ["Naija Life", 3, "The Igue Festival is celebrated in which kingdom?", "Benin", "Oyo", "Nri", "Bida"],
  ["Naija Life", 1, "In Lagos, what is a danfo?", "A yellow commercial bus", "A motorcycle taxi", "A tricycle", "A ferry"],
  ["Naija Life", 1, "What is an okada?", "A motorcycle taxi", "A yellow bus", "A tricycle", "A street food"],
  ["Naija Life", 1, "What is a keke?", "A tricycle taxi", "A motorcycle taxi", "A minibus", "A canoe"],
  ["Naija Life", 2, "Which bread is famously named after a Lagos area?", "Agege bread", "Ikeja bread", "Yaba bread", "Oshodi bread"],

  // Sports
  ["Football", 1, "What is the nickname of Nigeria's men's national football team?", "Super Eagles", "Super Falcons", "Black Stars", "Green Eagles"],
  ["Football", 1, "What is the nickname of Nigeria's women's national football team?", "Super Falcons", "Super Eagles", "Flying Eagles", "Golden Eaglets"],
  ["Football", 2, "Which Nigerian team plays at the U-17 level?", "Golden Eaglets", "Flying Eagles", "Dream Team", "Super Falcons"],
  ["Football", 2, "Which Nigerian team plays at the U-20 level?", "Flying Eagles", "Golden Eaglets", "Super Eagles B", "Olympic Eagles"],
  ["Football", 1, "In which year did Nigeria win Olympic football gold?", "1996", "1992", "2000", "2008"],
  ["Football", 2, "In which year did Nigeria win its first Africa Cup of Nations?", "1980", "1976", "1988", "1994"],
  ["Football", 2, "Nigeria won the Africa Cup of Nations in which of these years?", "2013", "2000", "2004", "2019"],
  ["Football", 2, "Nigeria co-hosted AFCON 2000 with which country?", "Ghana", "Cameroon", "Senegal", "Togo"],
  ["Sports", 2, "Who was the first Nigerian woman to win individual Olympic gold?", "Chioma Ajunwa", "Mary Onyali", "Blessing Okagbare", "Falilat Ogunkoya"],
  ["Sports", 2, "Tobi Amusan set a world record in which event?", "100m hurdles", "100m", "Long jump", "400m"],
  ["Sports", 1, "Hakeem Olajuwon became a legend in which sport?", "Basketball", "Football", "Boxing", "Tennis"],
  ["Football", 2, "Nwankwo Kanu won the Champions League with which club?", "Ajax", "Arsenal", "Inter Milan", "Barcelona"],
  ["Football", 2, "Who won the 2023 African Footballer of the Year?", "Victor Osimhen", "Mohamed Salah", "Sadio Mané", "Achraf Hakimi"],
  ["Football", 3, "Ademola Lookman scored a hat-trick in the 2024 Europa League final for which club?", "Atalanta", "Leicester City", "Fulham", "RB Leipzig"],
  ["Football", 1, "Which Nigerian legend was famous for his dribbling and nickname \"Jay-Jay\"?", "Austin Okocha", "Sunday Oliseh", "Daniel Amokachi", "Taribo West"],
  ["Football", 2, "Who scored the late winner for Nigeria in the 1996 Olympic final against Argentina?", "Emmanuel Amunike", "Nwankwo Kanu", "Daniel Amokachi", "Celestine Babayaro"],
  ["Football", 3, "Who was Nigeria's coach at the 1994 World Cup?", "Clemens Westerhof", "Bonfere Jo", "Shaibu Amodu", "Philippe Troussier"],
  ["Football", 2, "In which year did Nigeria first play at the FIFA World Cup?", "1994", "1990", "1998", "1982"],

  // Naija life: Naija talk
  ["Naija Life", 1, "In Nigerian Pidgin, what does \"wahala\" mean?", "Trouble", "Food", "Money", "Friend"],
  ["Naija Life", 1, "What does \"japa\" mean?", "To leave the country", "To get married", "To be broke", "To party"],
  ["Naija Life", 1, "What does \"sapa\" mean?", "Being broke", "Being rich", "Being tired", "Being lucky"],
  ["Naija Life", 1, "What is an \"owambe\"?", "A big party", "A market", "A church service", "A football match"],
  ["Naija Life", 1, "In Pidgin, what does \"abeg\" mean?", "Please", "Thank you", "Hello", "Sorry"],
  ["Naija Life", 1, "In Pidgin, what does \"chop\" mean?", "Eat", "Cut", "Run", "Sleep"],
  ["Naija Life", 1, "\"How far?\" usually means what?", "How are you? / What's up?", "How long is the trip?", "How much is it?", "Where are you going?"],
  ["Naija Life", 2, "In Yoruba, what does \"gbese\" mean?", "Debt", "Gift", "Party", "Food"],
  ["Naija Life", 1, "In Igbo, what does \"ndo\" mean?", "Sorry", "Thank you", "Welcome", "Goodbye"],
  ["Naija Life", 1, "In Igbo, what does \"daalu\" mean?", "Thank you", "Sorry", "Good morning", "Come here"],
  ["Naija Life", 1, "In Hausa, what does \"na gode\" mean?", "Thank you", "Good morning", "Sorry", "Welcome"],
  ["Naija Life", 1, "In Yoruba, what does \"e se\" mean?", "Thank you", "Good night", "Sorry", "Come in"],
  ["Naija Life", 1, "In Hausa, \"Ina kwana\" is a greeting for when?", "Morning", "Afternoon", "Evening", "Goodbye"],
  ["Naija Life", 1, "In Yoruba, \"E kaaro\" means what?", "Good morning", "Good night", "Welcome", "Well done"],
  ["Naija Life", 2, "In Igbo, \"Ututu oma\" means what?", "Good morning", "Good night", "Happy new year", "Safe journey"],
  ["Naija Life", 1, "In Hausa, what does \"sannu\" mean?", "Hello / greetings", "Goodbye", "Thank you", "Please"],
  ["Naija Life", 1, "In Nigerian slang, who is an \"oga\"?", "A boss", "A child", "A stranger", "A thief"],
  ["Naija Life", 1, "What is a \"go-slow\" in Nigeria?", "A traffic jam", "A lazy person", "A slow song", "A strike"],
  ["Naija Life", 2, "What is a \"JJC\"?", "A newcomer who doesn't know the ropes", "A big boss", "A church choir member", "A police officer"],
  ["Naija Life", 1, "What does \"no wahala\" mean?", "No problem", "No money", "No food", "No way"],

  // Nigeria: acronyms
  ["Nigeria", 1, "What does JAMB stand for?", "Joint Admissions and Matriculation Board", "Joint Academic Matriculation Board", "Junior Admissions and Matriculation Board", "Joint Admissions and Merit Board"],
  ["Nigeria", 1, "What does WAEC stand for?", "West African Examinations Council", "West African Education Council", "West African Exams Committee", "World African Examinations Council"],
  ["Nigeria", 1, "What does NECO stand for?", "National Examinations Council", "Nigerian Education Council", "National Education Commission", "Nigerian Examinations Committee"],
  ["Nigeria", 1, "What does UTME stand for?", "Unified Tertiary Matriculation Examination", "Universal Tertiary Matriculation Exam", "Unified Test for Matriculation Entry", "University Tertiary Merit Examination"],
  ["Nigeria", 1, "What does ASUU stand for?", "Academic Staff Union of Universities", "Association of State University Unions", "Academic Senate of Universities Union", "All Staff Union of Universities"],
  ["Nigeria", 1, "What does NIN stand for?", "National Identification Number", "Nigerian Identity Number", "National Identity Note", "Nigerian Individual Number"],
  ["Nigeria", 1, "What does BVN stand for?", "Bank Verification Number", "Bank Validation Number", "Banking Verification Note", "Bank Verified Name"],
  ["Nigeria", 2, "What does NIMC stand for?", "National Identity Management Commission", "Nigerian Identity Monitoring Council", "National ID Management Centre", "Nigerian Immigration Management Commission"],
  ["Nigeria", 1, "What does INEC stand for?", "Independent National Electoral Commission", "Independent Nigerian Election Council", "Interim National Electoral Commission", "Independent National Election Committee"],
  ["Nigeria", 1, "What does EFCC stand for?", "Economic and Financial Crimes Commission", "Economic and Fraud Control Commission", "Economic and Financial Crimes Council", "Executive Financial Crimes Commission"],
  ["Nigeria", 1, "What does FRSC stand for?", "Federal Road Safety Corps", "Federal Road Service Commission", "Federal Roads and Safety Council", "Federal Road Security Corps"],
  ["Nigeria", 2, "What does NAFDAC stand for?", "National Agency for Food and Drug Administration and Control", "National Authority for Food, Drugs and Chemicals", "Nigerian Agency for Food and Drug Control", "National Administration for Food and Drug Certification"],
  ["Nigeria", 2, "What does LASTMA stand for?", "Lagos State Traffic Management Authority", "Lagos State Transport Monitoring Agency", "Lagos Area Street Traffic Management Authority", "Lagos State Traffic Monitoring Association"],
  ["Nigeria", 1, "What does BRT stand for?", "Bus Rapid Transit", "Bus Route Transport", "Bus Rail Transit", "Basic Road Transport"],
  ["Nigeria", 2, "What does ECOWAS stand for?", "Economic Community of West African States", "Economic Council of West African States", "Economic Community of West Africa Societies", "Economic Cooperation of West African States"],
  ["Nigeria", 2, "What does CBN stand for?", "Central Bank of Nigeria", "Commercial Bank of Nigeria", "Central Banking Network", "Capital Bank of Nigeria"],
  ["Nigeria", 2, "What does NCC stand for in telecoms?", "Nigerian Communications Commission", "National Communications Council", "Nigerian Cable Commission", "National Connectivity Commission"],
  ["Nigeria", 2, "What does NDLEA stand for?", "National Drug Law Enforcement Agency", "Nigerian Drug and Liquor Enforcement Agency", "National Drug Licensing and Enforcement Authority", "Nigerian Drug Law Enforcement Association"],

  // Africa and the world
  ["General", 1, "What is the capital of Ghana?", "Accra", "Kumasi", "Lomé", "Tamale"],
  ["General", 1, "What is the capital of Kenya?", "Nairobi", "Mombasa", "Kampala", "Dar es Salaam"],
  ["General", 1, "Which is the most populous country in Africa?", "Nigeria", "Ethiopia", "Egypt", "DR Congo"],
  ["General", 2, "Which is the largest country in Africa by area?", "Algeria", "Nigeria", "DR Congo", "Sudan"],
  ["General", 1, "What is the highest mountain in Africa?", "Mount Kilimanjaro", "Mount Kenya", "Mount Cameroon", "Mount Stanley"],
  ["General", 1, "What is the longest river in Africa?", "The Nile", "The Niger", "The Congo", "The Zambezi"],
  ["General", 2, "Where is the African Union headquarters?", "Addis Ababa", "Abuja", "Nairobi", "Johannesburg"],
  ["General", 1, "Nelson Mandela was president of which country?", "South Africa", "Zimbabwe", "Namibia", "Botswana"],
  ["General", 1, "Which planet is known as the Red Planet?", "Mars", "Jupiter", "Venus", "Mercury"],
  ["General", 1, "What is the chemical symbol for water?", "H2O", "CO2", "O2", "NaCl"],
  ["General", 1, "How many continents are there?", "7", "5", "6", "8"],
  ["General", 1, "What is the largest ocean on Earth?", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  ["General", 2, "Which gas do plants take in from the air to make food?", "Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
  ["General", 1, "Which organ pumps blood around the body?", "The heart", "The lungs", "The liver", "The kidneys"],
  ["General", 2, "What is the capital of Senegal?", "Dakar", "Bamako", "Banjul", "Conakry"],
  ["General", 2, "What is the capital of Cameroon?", "Yaoundé", "Douala", "Bamenda", "Garoua"],
  ["General", 2, "Which country's currency is the cedi?", "Ghana", "Kenya", "Gambia", "Sierra Leone"],
  ["General", 2, "In 2020 Stripe bought which Nigerian payments company?", "Paystack", "Flutterwave", "Interswitch", "Opay"],
  ["General", 1, "Who founded the Dangote Group?", "Aliko Dangote", "Femi Otedola", "Mike Adenuga", "Tony Elumelu"],
  ["General", 2, "Which company runs the Glo mobile network?", "Globacom", "MTN", "Airtel", "9mobile"],

  // Football
  ["Football", 1, "Which country won the 2022 FIFA World Cup?", "Argentina", "France", "Brazil", "Croatia"],
  ["Football", 1, "Which country hosted the 2022 FIFA World Cup?", "Qatar", "Russia", "Saudi Arabia", "United Arab Emirates"],
  ["Football", 2, "Who won the Golden Boot at the 2022 World Cup?", "Kylian Mbappé", "Lionel Messi", "Olivier Giroud", "Julián Álvarez"],
  ["Football", 1, "Which country won the 2018 FIFA World Cup?", "France", "Croatia", "Germany", "Belgium"],
  ["Football", 2, "Which country won the 2014 FIFA World Cup?", "Germany", "Argentina", "Brazil", "Netherlands"],
  ["Football", 2, "By what score did Germany beat Brazil in the 2014 World Cup semi-final?", "7-1", "5-0", "4-1", "6-2"],
  ["Football", 1, "Which was the first World Cup held in Africa?", "South Africa 2010", "Egypt 2006", "Morocco 2014", "Nigeria 2002"],
  ["Football", 1, "Which country has won the most FIFA World Cups?", "Brazil", "Germany", "Italy", "Argentina"],
  ["Football", 2, "Which three countries are hosting the 2026 World Cup?", "USA, Canada and Mexico", "USA, Mexico and Brazil", "Canada, USA and Argentina", "Spain, Portugal and Morocco"],
  ["Football", 2, "In 2022, which became the first African team to reach a World Cup semi-final?", "Morocco", "Senegal", "Cameroon", "Ghana"],
  ["Football", 1, "Which club has won the most Champions League / European Cup titles?", "Real Madrid", "AC Milan", "Bayern Munich", "Barcelona"],
  ["Football", 2, "Which club won its first Champions League title in 2025?", "Paris Saint-Germain", "Arsenal", "Manchester City", "Inter Milan"],
  ["Football", 1, "Which player has won the most Ballon d'Or awards?", "Lionel Messi", "Cristiano Ronaldo", "Michel Platini", "Johan Cruyff"],
  ["Football", 2, "Who won the 2024 Ballon d'Or?", "Rodri", "Vinícius Júnior", "Jude Bellingham", "Erling Haaland"],
  ["Football", 3, "Which African player won the Ballon d'Or in 1995?", "George Weah", "Abedi Pele", "Roger Milla", "Nwankwo Kanu"],
  ["Football", 1, "Which country won Euro 2024?", "Spain", "England", "France", "Germany"],
  ["Football", 2, "Which country won Euro 2020 (played in 2021)?", "Italy", "England", "Spain", "Portugal"],
  ["Football", 2, "Which country won the 2023 Africa Cup of Nations, beating Nigeria in the final?", "Ivory Coast", "South Africa", "Egypt", "Senegal"],
  ["Football", 2, "Which country has won the most Africa Cup of Nations titles?", "Egypt", "Cameroon", "Ghana", "Nigeria"],
  ["Football", 1, "In which year was the Premier League founded?", "1992", "1985", "1999", "1888"],
  ["Football", 2, "Which team went a whole Premier League season unbeaten in 2003-04?", "Arsenal", "Manchester United", "Chelsea", "Liverpool"],
  ["Football", 2, "Which club shocked everyone by winning the 2015-16 Premier League?", "Leicester City", "Tottenham Hotspur", "West Ham United", "Everton"],
  ["Football", 2, "Who is the Premier League's all-time top scorer?", "Alan Shearer", "Wayne Rooney", "Thierry Henry", "Sergio Agüero"],
  ["Football", 1, "Which club is nicknamed the Red Devils?", "Manchester United", "Liverpool", "Arsenal", "AC Milan"],
  ["Football", 1, "Which club is nicknamed the Gunners?", "Arsenal", "Chelsea", "Tottenham Hotspur", "West Ham United"],
  ["Football", 2, "Which club is nicknamed the Toffees?", "Everton", "Fulham", "Aston Villa", "Wolves"],
  ["Football", 2, "Which club is nicknamed the Magpies?", "Newcastle United", "West Ham United", "Brighton", "Crystal Palace"],
  ["Football", 2, "Which club is nicknamed the Hammers?", "West Ham United", "Brentford", "Burnley", "Sheffield United"],
  ["Football", 1, "Which club's fans sing \"You'll Never Walk Alone\"?", "Liverpool", "Manchester United", "Arsenal", "Chelsea"],
  ["Football", 1, "Which club plays at Old Trafford?", "Manchester United", "Manchester City", "Liverpool", "Everton"],
  ["Football", 1, "Which club plays at Anfield?", "Liverpool", "Everton", "Chelsea", "Leeds United"],
  ["Football", 1, "Which club plays at Stamford Bridge?", "Chelsea", "Arsenal", "Fulham", "Tottenham Hotspur"],
  ["Football", 1, "Which club plays at the Camp Nou?", "Barcelona", "Real Madrid", "Atlético Madrid", "Valencia"],
  ["Football", 1, "Which club plays at the Santiago Bernabéu?", "Real Madrid", "Barcelona", "Sevilla", "Atlético Madrid"],
  ["Football", 2, "Which club plays at the Allianz Arena?", "Bayern Munich", "Borussia Dortmund", "Juventus", "RB Leipzig"],
  ["Football", 1, "El Clásico is played between which two clubs?", "Real Madrid and Barcelona", "Barcelona and Atlético Madrid", "Real Madrid and Atlético Madrid", "Sevilla and Real Betis"],
  ["Football", 2, "The North London derby is between Arsenal and which club?", "Tottenham Hotspur", "Chelsea", "West Ham United", "Fulham"],
  ["Football", 2, "The Merseyside derby is between Liverpool and which club?", "Everton", "Manchester United", "Leeds United", "Tranmere Rovers"],
  ["Football", 2, "The Milan derby is between AC Milan and which club?", "Inter Milan", "Juventus", "Napoli", "AS Roma"],
  ["Football", 1, "What does VAR stand for?", "Video Assistant Referee", "Visual Action Replay", "Video Action Review", "Virtual Assistant Ruling"],
  ["Football", 1, "How many players does each team have on the pitch in football?", "11", "10", "12", "9"],
  ["Football", 1, "How many yellow cards in one match get a player sent off?", "2", "1", "3", "4"],
  ["Football", 1, "What is it called when a player scores three goals in one match?", "A hat-trick", "A brace", "A treble", "A clean sheet"],
  ["Football", 1, "What does CR7 stand for?", "Cristiano Ronaldo, number 7", "Cristiano Ronaldo's 7 titles", "Club Real 7", "Captain Ronaldo 7"],
  ["Football", 2, "Which club did Cristiano Ronaldo start his professional career at?", "Sporting CP", "Manchester United", "Benfica", "Porto"],
  ["Football", 2, "Which club did Lionel Messi join in 2023?", "Inter Miami", "Al Hilal", "Barcelona", "LA Galaxy"],
  ["Football", 2, "Which Saudi club did Cristiano Ronaldo join in 2023?", "Al Nassr", "Al Hilal", "Al Ittihad", "Al Ahli"],
  ["Football", 2, "Which club did Kylian Mbappé join in 2024?", "Real Madrid", "Liverpool", "Barcelona", "Manchester City"],
  ["Football", 1, "Which country does Erling Haaland play for?", "Norway", "Sweden", "Denmark", "Iceland"],
  ["Football", 1, "Which country does Mohamed Salah play for?", "Egypt", "Morocco", "Algeria", "Tunisia"],
  ["Football", 1, "Which country did Didier Drogba play for?", "Ivory Coast", "Ghana", "Cameroon", "Senegal"],
  ["Football", 1, "Which country did Samuel Eto'o play for?", "Cameroon", "Nigeria", "Ivory Coast", "Gabon"],
  ["Football", 2, "Which club did Sir Alex Ferguson manage for 26 years?", "Manchester United", "Aberdeen", "Celtic", "Liverpool"],
  ["Football", 2, "Which manager called himself \"The Special One\"?", "José Mourinho", "Pep Guardiola", "Arsène Wenger", "Carlo Ancelotti"],
  ["Football", 2, "Diego Maradona's \"Hand of God\" goal was against which team?", "England", "Germany", "Brazil", "Italy"],
  ["Football", 2, "Zinedine Zidane was sent off for a headbutt in which World Cup final?", "2006", "1998", "2002", "2010"],
  ["Football", 1, "Pelé played for which country?", "Brazil", "Argentina", "Portugal", "Uruguay"],
  ["Football", 2, "Which country won the 2024 Copa América?", "Argentina", "Colombia", "Brazil", "Uruguay"],

  // Sports
  ["Sports", 1, "Usain Bolt is from which country?", "Jamaica", "USA", "Trinidad and Tobago", "Bahamas"],
  ["Sports", 2, "What is Usain Bolt's 100m world record time?", "9.58 seconds", "9.69 seconds", "9.72 seconds", "9.49 seconds"],
  ["Sports", 1, "Michael Jordan won six NBA titles with which team?", "Chicago Bulls", "Los Angeles Lakers", "Boston Celtics", "Miami Heat"],
  ["Sports", 2, "Which NBA star of Nigerian parents is called the \"Greek Freak\"?", "Giannis Antetokounmpo", "Joel Embiid", "Hakeem Olajuwon", "Precious Achiuwa"],
  ["Sports", 1, "How many players does a basketball team have on court?", "5", "6", "7", "11"],
  ["Sports", 2, "How many Grand Slam singles titles did Serena Williams win?", "23", "18", "20", "24"],
  ["Sports", 2, "Which tennis Grand Slam is played on grass?", "Wimbledon", "French Open", "US Open", "Australian Open"],
  ["Sports", 2, "Which tennis Grand Slam is played on clay?", "French Open", "Wimbledon", "US Open", "Australian Open"],
  ["Sports", 2, "Which Formula 1 team did Lewis Hamilton join in 2025?", "Ferrari", "Red Bull", "McLaren", "Aston Martin"],
  ["Sports", 2, "UFC champion Israel Adesanya was born in which Nigerian city?", "Lagos", "Ibadan", "Abuja", "Port Harcourt"],
  ["Sports", 2, "Which UFC champion is nicknamed \"The Nigerian Nightmare\"?", "Kamaru Usman", "Israel Adesanya", "Francis Ngannou", "Sodiq Yusuff"],
  ["Sports", 1, "Anthony Joshua is famous in which sport?", "Boxing", "Wrestling", "UFC", "Athletics"],
  ["Sports", 1, "Which city hosted the 2024 Summer Olympics?", "Paris", "Tokyo", "Los Angeles", "London"],
  ["Sports", 2, "Which city will host the 2028 Summer Olympics?", "Los Angeles", "Brisbane", "Paris", "Madrid"],
  ["Sports", 2, "How long is a marathon?", "42.195 km", "40 km", "26 km", "50 km"],
  ["Sports", 1, "The Super Bowl is the final of which sport?", "American football", "Basketball", "Baseball", "Ice hockey"],
  ["Sports", 1, "Who said \"Float like a butterfly, sting like a bee\"?", "Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Joe Frazier"],

  // Music
  ["Music", 1, "Who is known as the King of Pop?", "Michael Jackson", "Elvis Presley", "Prince", "Usher"],
  ["Music", 2, "Which Michael Jackson album is the best-selling album of all time?", "Thriller", "Bad", "Off the Wall", "Dangerous"],
  ["Music", 1, "Beyoncé first found fame in which group?", "Destiny's Child", "TLC", "En Vogue", "The Pussycat Dolls"],
  ["Music", 1, "Which rapper is married to Beyoncé?", "Jay-Z", "Kanye West", "Drake", "Nas"],
  ["Music", 2, "Which Beyoncé album won Album of the Year at the 2025 Grammys?", "Cowboy Carter", "Renaissance", "Lemonade", "4"],
  ["Music", 1, "Rihanna is from which country?", "Barbados", "Jamaica", "Trinidad and Tobago", "Bahamas"],
  ["Music", 1, "What is the name of Rihanna's beauty brand?", "Fenty Beauty", "Rare Beauty", "Kylie Cosmetics", "Glossier"],
  ["Music", 1, "Drake is from which country?", "Canada", "USA", "UK", "Jamaica"],
  ["Music", 2, "Which Kendrick Lamar diss track aimed at Drake became a huge 2024 hit?", "Not Like Us", "Alright", "Humble", "Family Matters"],
  ["Music", 2, "Who headlined the Super Bowl halftime show in February 2025?", "Kendrick Lamar", "Drake", "Rihanna", "Usher"],
  ["Music", 3, "Which rapper won the Pulitzer Prize for Music in 2018?", "Kendrick Lamar", "J. Cole", "Jay-Z", "Eminem"],
  ["Music", 1, "What is the name of Taylor Swift's record-breaking tour?", "The Eras Tour", "The Reputation Tour", "The Midnights Tour", "The Lover Tour"],
  ["Music", 1, "What are Taylor Swift's fans called?", "Swifties", "Taylorites", "Beyhive", "Barbz"],
  ["Music", 1, "What are Beyoncé's fans called?", "The Beyhive", "Swifties", "The Navy", "Barbz"],
  ["Music", 1, "What are Nicki Minaj's fans called?", "Barbz", "Beyhive", "Navy", "Lambs"],
  ["Music", 1, "BTS is a music group from which country?", "South Korea", "Japan", "China", "Thailand"],
  ["Music", 1, "What are BTS fans called?", "ARMY", "Blinks", "Swifties", "Directioners"],
  ["Music", 2, "How many members are in Blackpink?", "4", "3", "5", "7"],
  ["Music", 1, "Who sang \"Shape of You\"?", "Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Sam Smith"],
  ["Music", 1, "Who sang \"Blinding Lights\"?", "The Weeknd", "Bruno Mars", "Post Malone", "Harry Styles"],
  ["Music", 2, "Adele names her albums after what?", "Her age", "Cities", "Her children", "Colours"],
  ["Music", 1, "Bob Marley was from which country?", "Jamaica", "Barbados", "Haiti", "Trinidad and Tobago"],
  ["Music", 1, "Amapiano music started in which country?", "South Africa", "Nigeria", "Ghana", "Kenya"],
  ["Music", 2, "Tyla won the first Grammy for Best African Music Performance with which song?", "Water", "Truth or Dare", "Jump", "Push 2 Start"],
  ["Music", 1, "Davido released which album in 2023?", "Timeless", "A Better Time", "A Good Time", "Omo Baba Olowo"],
  ["Music", 2, "Asake's 2022 debut album is called what?", "Mr. Money with the Vibe", "Work of Art", "Lungu Boy", "Ololade"],
  ["Music", 2, "Rema's debut album is called what?", "Rave & Roses", "HEIS", "Afrorave", "Calm Down"],
  ["Music", 1, "Wizkid's 2020 album with the hit \"Essence\" is called what?", "Made in Lagos", "Ayo", "Sounds from the Other Side", "More Love, Less Ego"],
  ["Music", 1, "Which Ayra Starr song became a big hit in 2022?", "Rush", "Love Nwantiti", "Peru", "Buga"],
  ["Music", 1, "Who sang \"Love Nwantiti\"?", "CKay", "Joeboy", "Fireboy DML", "Omah Lay"],
  ["Music", 1, "Who sang \"Buga\" with Tekno?", "Kizz Daniel", "Olamide", "Patoranking", "Zinoleesky"],
  ["Music", 1, "Who sang \"Peru\", later remixed with Ed Sheeran?", "Fireboy DML", "Rema", "Ruger", "Joeboy"],
  ["Music", 2, "Burna Boy's \"Last Last\" samples which Toni Braxton song?", "He Wasn't Man Enough", "Un-Break My Heart", "Breathe Again", "Another Sad Love Song"],
  ["Music", 2, "Which South African artist is on Davido's \"Unavailable\"?", "Musa Keys", "Master KG", "Kabza De Small", "Focalistic"],
  ["Music", 1, "What is Burna Boy's real name?", "Damini Ogulu", "Ayodeji Balogun", "David Adeleke", "Divine Ikubor"],
  ["Music", 1, "What is Wizkid's real name?", "Ayodeji Balogun", "Damini Ogulu", "Ahmed Ololade", "Oluwatosin Ajibade"],
  ["Music", 1, "What is Davido's real name?", "David Adeleke", "David Adedeji", "David Okonkwo", "David Ibrahim"],
  ["Music", 2, "What is Rema's real name?", "Divine Ikubor", "Divine Okafor", "Remi Adebayo", "Emeka Ikubor"],
  ["Music", 2, "What is Tems' real name?", "Temilade Openiyi", "Temitope Adeyemi", "Temidayo Balogun", "Temiloluwa Ojo"],
  ["Music", 2, "What is Asake's real name?", "Ahmed Ololade", "Adewale Ololade", "Azeez Fashola", "Ahmed Bakare"],
  ["Music", 1, "What is Eminem's real name?", "Marshall Mathers", "Curtis Jackson", "Shawn Carter", "Calvin Broadus"],
  ["Music", 1, "What is Drake's real first name?", "Aubrey", "Andre", "Aaron", "Austin"],
  ["Music", 1, "What is Rihanna's real first name?", "Robyn", "Rachel", "Rebecca", "Rhonda"],
  ["Music", 1, "Which Shakira song was the anthem of the 2010 World Cup?", "Waka Waka", "Hips Don't Lie", "Whenever, Wherever", "La La La"],
  ["Music", 1, "Shakira is from which country?", "Colombia", "Mexico", "Spain", "Argentina"],
  ["Music", 2, "Which song was the first YouTube video to reach one billion views?", "Gangnam Style", "Despacito", "Baby", "See You Again"],
  ["Music", 1, "Who sang \"Despacito\" with Daddy Yankee?", "Luis Fonsi", "J Balvin", "Bad Bunny", "Enrique Iglesias"],
  ["Music", 1, "Spotify was founded in which country?", "Sweden", "USA", "UK", "Germany"],
  ["Music", 2, "Coachella is a famous music festival in which US state?", "California", "Texas", "Florida", "New York"],

  // Movies & TV
  ["Movies & TV", 1, "Which film is set in the African nation of Wakanda?", "Black Panther", "Coming to America", "The Woman King", "Blood Diamond"],
  ["Movies & TV", 1, "Who played T'Challa in \"Black Panther\" (2018)?", "Chadwick Boseman", "Michael B. Jordan", "Daniel Kaluuya", "John Boyega"],
  ["Movies & TV", 1, "\"Squid Game\" comes from which country?", "South Korea", "Japan", "China", "Taiwan"],
  ["Movies & TV", 1, "What is the original Spanish title of \"Money Heist\"?", "La Casa de Papel", "El Profesor", "La Casa de Dinero", "El Atraco"],
  ["Movies & TV", 1, "\"Game of Thrones\" is based on books by whom?", "George R.R. Martin", "J.R.R. Tolkien", "Stephen King", "J.K. Rowling"],
  ["Movies & TV", 1, "Which show is a prequel to \"Game of Thrones\"?", "House of the Dragon", "The Witcher", "Vikings", "The Rings of Power"],
  ["Movies & TV", 1, "In \"Breaking Bad\", what subject did Walter White teach?", "Chemistry", "Biology", "Physics", "Maths"],
  ["Movies & TV", 2, "In which fictional town is \"Stranger Things\" set?", "Hawkins", "Riverdale", "Springfield", "Derry"],
  ["Movies & TV", 1, "What is the coffee shop in \"Friends\" called?", "Central Perk", "Java Joe's", "The Daily Grind", "Coffee Bean"],
  ["Movies & TV", 1, "Which school does Harry Potter go to?", "Hogwarts", "Durmstrang", "Beauxbatons", "Brakebills"],
  ["Movies & TV", 1, "What is Iron Man's real name?", "Tony Stark", "Steve Rogers", "Bruce Banner", "Peter Parker"],
  ["Movies & TV", 1, "What is Spider-Man's real name?", "Peter Parker", "Bruce Wayne", "Clark Kent", "Miles Morales"],
  ["Movies & TV", 2, "What is the name of Thor's hammer?", "Mjolnir", "Stormbreaker", "Gungnir", "Excalibur"],
  ["Movies & TV", 2, "How many Infinity Stones are there in the Marvel films?", "6", "5", "7", "9"],
  ["Movies & TV", 1, "Which city does Batman protect?", "Gotham City", "Metropolis", "Star City", "Central City"],
  ["Movies & TV", 1, "Superman comes from which planet?", "Krypton", "Vulcan", "Asgard", "Tatooine"],
  ["Movies & TV", 1, "In \"The Lion King\", who is Simba's father?", "Mufasa", "Scar", "Rafiki", "Zazu"],
  ["Movies & TV", 1, "Which song does Elsa sing in \"Frozen\"?", "Let It Go", "How Far I'll Go", "Into the Unknown", "Part of Your World"],
  ["Movies & TV", 1, "Who directed \"Titanic\"?", "James Cameron", "Steven Spielberg", "Christopher Nolan", "Ridley Scott"],
  ["Movies & TV", 2, "Which was the first non-English film to win the Oscar for Best Picture?", "Parasite", "Roma", "Squid Game", "Crouching Tiger, Hidden Dragon"],
  ["Movies & TV", 2, "Which film won Best Picture at the 2024 Oscars?", "Oppenheimer", "Barbie", "Poor Things", "Killers of the Flower Moon"],
  ["Movies & TV", 1, "Who directed the 2023 film \"Barbie\"?", "Greta Gerwig", "Sofia Coppola", "Ava DuVernay", "Patty Jenkins"],
  ["Movies & TV", 2, "Who directed the Nollywood hit \"King of Boys\"?", "Kemi Adetiba", "Kunle Afolayan", "Funke Akindele", "Jade Osiberu"],
  ["Movies & TV", 2, "Who directed the Netflix film \"Anikulapo\"?", "Kunle Afolayan", "Kemi Adetiba", "Niyi Akinmolayan", "Tunde Kelani"],
  ["Movies & TV", 2, "\"Lionheart\" was directed by and starred which actress?", "Genevieve Nnaji", "Omotola Jalade-Ekeinde", "Rita Dominic", "Funke Akindele"],
  ["Movies & TV", 1, "Which actress plays Wednesday Addams in the Netflix series \"Wednesday\"?", "Jenna Ortega", "Zendaya", "Millie Bobby Brown", "Sadie Sink"],
  ["Movies & TV", 2, "\"Peaky Blinders\" is set in which city?", "Birmingham", "London", "Manchester", "Liverpool"],
  ["Movies & TV", 1, "Which Pixar film takes place inside a girl's mind with characters like Joy and Sadness?", "Inside Out", "Soul", "Coco", "Up"],
  ["Movies & TV", 1, "In \"Fast & Furious\", what is Vin Diesel's character called?", "Dominic Toretto", "Brian O'Conner", "Luke Hobbs", "Deckard Shaw"],
  ["Movies & TV", 1, "What is James Bond's code number?", "007", "001", "009", "700"],
  ["Movies & TV", 1, "Who plays John Wick?", "Keanu Reeves", "Tom Cruise", "Jason Statham", "Liam Neeson"],
  ["Movies & TV", 2, "\"The Woman King\" is about the women warriors of which kingdom?", "Dahomey", "Benin", "Ashanti", "Oyo"],
  ["Movies & TV", 1, "In \"Coming to America\", Prince Akeem comes from which country?", "Zamunda", "Wakanda", "Genovia", "Sokovia"],
  ["Movies & TV", 1, "In \"Tom and Jerry\", what kind of animal is Tom?", "A cat", "A dog", "A mouse", "A rabbit"],
  ["Movies & TV", 1, "What is Shrek?", "An ogre", "A troll", "A giant", "A goblin"],
  ["Movies & TV", 2, "At the 2022 Oscars, Will Smith slapped which comedian?", "Chris Rock", "Kevin Hart", "Dave Chappelle", "Jimmy Kimmel"],
  ["Movies & TV", 2, "Christopher Nolan directed which of these films?", "Inception", "Avatar", "Jurassic Park", "The Matrix"],

  // Fashion
  ["Fashion", 1, "What is Nike's logo called?", "The Swoosh", "The Tick", "The Wing", "The Flash"],
  ["Fashion", 1, "What is Nike's famous slogan?", "Just Do It", "Impossible Is Nothing", "Forever Faster", "Think Different"],
  ["Fashion", 1, "Which brand's slogan is \"Impossible Is Nothing\"?", "Adidas", "Nike", "Puma", "Reebok"],
  ["Fashion", 1, "Adidas is from which country?", "Germany", "USA", "Italy", "France"],
  ["Fashion", 1, "How many stripes are in the classic Adidas logo?", "3", "2", "4", "5"],
  ["Fashion", 1, "Which animal is on the Puma logo?", "A puma (big cat)", "A horse", "A crocodile", "An eagle"],
  ["Fashion", 1, "Which animal is on the Lacoste logo?", "A crocodile", "A puma", "A horse", "A tiger"],
  ["Fashion", 2, "Which mythical figure is on the Versace logo?", "Medusa", "Zeus", "Athena", "Poseidon"],
  ["Fashion", 1, "Gucci is from which country?", "Italy", "France", "Spain", "Switzerland"],
  ["Fashion", 1, "Louis Vuitton is from which country?", "France", "Italy", "UK", "Belgium"],
  ["Fashion", 1, "Who founded Chanel?", "Coco Chanel", "Christian Dior", "Yves Saint Laurent", "Hubert de Givenchy"],
  ["Fashion", 2, "The famous Birkin bag is made by which brand?", "Hermès", "Chanel", "Louis Vuitton", "Prada"],
  ["Fashion", 2, "Burberry is famous for which pattern?", "Check (tartan)", "Polka dots", "Leopard print", "Pinstripes"],
  ["Fashion", 1, "Which brand's logo shows a polo player on a horse?", "Ralph Lauren", "Lacoste", "Tommy Hilfiger", "Hermès"],
  ["Fashion", 1, "Air Jordans are named after which athlete?", "Michael Jordan", "Jordan Henderson", "Jordan Clarkson", "Michael B. Jordan"],
  ["Fashion", 2, "Converse's classic sneaker is named after whom?", "Chuck Taylor", "Stan Smith", "Rod Laver", "Jack Purcell"],
  ["Fashion", 2, "The Stan Smith sneaker is made by which brand?", "Adidas", "Nike", "Puma", "Reebok"],
  ["Fashion", 2, "Who founded the brand Off-White?", "Virgil Abloh", "Kanye West", "Pharrell Williams", "Jerry Lorenzo"],
  ["Fashion", 2, "Which rapper created the Yeezy brand?", "Kanye West", "Travis Scott", "Jay-Z", "A$AP Rocky"],
  ["Fashion", 1, "Rihanna's fashion and beauty brand is called what?", "Fenty", "Skims", "Ivy Park", "Savage"],
  ["Fashion", 2, "Which brand did Beyoncé create?", "Ivy Park", "Fenty", "Skims", "Good American"],
  ["Fashion", 2, "Kim Kardashian co-founded which shapewear brand?", "Skims", "Spanx", "Fenty", "Savage X"],
  ["Fashion", 1, "In which city is the Met Gala held?", "New York", "Paris", "Los Angeles", "Milan"],
  ["Fashion", 2, "On which day is the Met Gala usually held?", "The first Monday in May", "New Year's Eve", "The last Friday in June", "Valentine's Day"],
  ["Fashion", 2, "Which of these is NOT one of the \"Big Four\" fashion weeks?", "Lagos", "Paris", "Milan", "London"],
  ["Fashion", 1, "Zara is from which country?", "Spain", "Italy", "France", "Sweden"],
  ["Fashion", 1, "H&M is from which country?", "Sweden", "Germany", "Denmark", "Netherlands"],
  ["Fashion", 1, "Uniqlo is from which country?", "Japan", "South Korea", "China", "Singapore"],
  ["Fashion", 1, "Rolex watches are made in which country?", "Switzerland", "Germany", "Italy", "Japan"],
  ["Fashion", 2, "Streetwear brand Supreme started in which city?", "New York", "Los Angeles", "London", "Tokyo"],
  ["Fashion", 1, "What is an agbada?", "A flowing wide-sleeved robe", "A head tie", "A beaded necklace", "A wrapper skirt"],
  ["Fashion", 1, "What is a gele?", "A head tie", "A cap", "A wrapper", "A shawl"],
  ["Fashion", 1, "What is \"aso ebi\"?", "Matching outfits worn by a group at an event", "A type of shoe", "A hand-woven bag", "A wedding cake"],
  ["Fashion", 2, "Adire, the indigo tie-dye cloth, is famous in which city?", "Abeokuta", "Kano", "Onitsha", "Calabar"],
  ["Fashion", 2, "Isiagu, the shirt with lion heads, is traditional wear of which people?", "Igbo", "Yoruba", "Hausa", "Tiv"],
  ["Fashion", 2, "Aso-oke is a hand-woven cloth of which people?", "Yoruba", "Igbo", "Efik", "Kanuri"],
  ["Fashion", 1, "What do Nigerians call second-hand clothes?", "Okrika", "Ankara", "Aso ebi", "Lace"],
  ["Fashion", 1, "Denim is usually made from what?", "Cotton", "Silk", "Wool", "Polyester"],
  ["Fashion", 2, "What does \"haute couture\" mean in fashion?", "High-end made-to-measure fashion", "Cheap mass-produced clothes", "Second-hand designer clothes", "Sportswear"],

  // Tech & Internet
  ["Tech & Internet", 1, "Which company makes ChatGPT?", "OpenAI", "Google", "Meta", "Microsoft"],
  ["Tech & Internet", 1, "Which company owns WhatsApp?", "Meta", "Google", "Microsoft", "Apple"],
  ["Tech & Internet", 1, "Which company owns Instagram?", "Meta", "Google", "Snap", "ByteDance"],
  ["Tech & Internet", 1, "Who founded Facebook?", "Mark Zuckerberg", "Jack Dorsey", "Elon Musk", "Larry Page"],
  ["Tech & Internet", 1, "What was Twitter renamed to in 2023?", "X", "Threads", "Bird", "Tweet"],
  ["Tech & Internet", 1, "Which company created TikTok?", "ByteDance", "Tencent", "Alibaba", "Meta"],
  ["Tech & Internet", 1, "In which year was the first iPhone released?", "2007", "2005", "2010", "2001"],
  ["Tech & Internet", 1, "Who co-founded Apple with Steve Wozniak?", "Steve Jobs", "Bill Gates", "Tim Cook", "Larry Ellison"],
  ["Tech & Internet", 2, "Who founded Google?", "Larry Page and Sergey Brin", "Bill Gates and Paul Allen", "Steve Jobs and Steve Wozniak", "Jeff Bezos and Elon Musk"],
  ["Tech & Internet", 1, "Who founded Amazon?", "Jeff Bezos", "Elon Musk", "Bill Gates", "Jack Ma"],
  ["Tech & Internet", 1, "Who founded SpaceX?", "Elon Musk", "Jeff Bezos", "Richard Branson", "Mark Zuckerberg"],
  ["Tech & Internet", 1, "Which company makes Android?", "Google", "Samsung", "Apple", "Microsoft"],
  ["Tech & Internet", 1, "Samsung is from which country?", "South Korea", "Japan", "China", "Taiwan"],
  ["Tech & Internet", 2, "Tecno, Infinix and itel phones are made by which company?", "Transsion", "Xiaomi", "Huawei", "Samsung"],
  ["Tech & Internet", 1, "Which company owns YouTube?", "Google", "Meta", "Microsoft", "Amazon"],
  ["Tech & Internet", 2, "Who invented the World Wide Web?", "Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Alan Turing"],
  ["Tech & Internet", 1, "What does AI stand for?", "Artificial Intelligence", "Automated Internet", "Advanced Interface", "Applied Information"],
  ["Tech & Internet", 1, "What does PDF stand for?", "Portable Document Format", "Printed Data File", "Public Document File", "Personal Data Format"],
  ["Tech & Internet", 1, "What does OTP stand for?", "One-Time Password", "Online Transfer PIN", "Official Text Pin", "Open Transaction Protocol"],
  ["Tech & Internet", 2, "What does CPU stand for?", "Central Processing Unit", "Computer Power Unit", "Central Program Utility", "Core Processing Unit"],
  ["Tech & Internet", 2, "What does RAM stand for?", "Random Access Memory", "Read And Memorise", "Rapid Action Memory", "Remote Access Module"],
  ["Tech & Internet", 1, "What does USB stand for?", "Universal Serial Bus", "United System Board", "Universal Storage Box", "User Service Bus"],
  ["Tech & Internet", 2, "What does URL stand for?", "Uniform Resource Locator", "Universal Record Link", "User Reference Link", "Unified Resource Line"],
  ["Tech & Internet", 1, "What does GPS stand for?", "Global Positioning System", "General Phone Service", "Geo Path Satellite", "Global Pointer Signal"],
  ["Tech & Internet", 2, "What is the name used by Bitcoin's anonymous creator?", "Satoshi Nakamoto", "Vitalik Buterin", "Hal Finney", "Nick Szabo"],
  ["Tech & Internet", 1, "Which app has a ghost as its logo?", "Snapchat", "TikTok", "Telegram", "Signal"],
  ["Tech & Internet", 2, "Emoji were first created in which country?", "Japan", "USA", "South Korea", "China"],
  ["Tech & Internet", 2, "Netflix started as a business that did what?", "Rented DVDs by post", "Sold TVs", "Made video games", "Ran cinemas"],
  ["Tech & Internet", 2, "Who co-founded Paystack?", "Shola Akinlade", "Olugbenga Agboola", "Iyin Aboyeji", "Tosin Eniolorunda"],
  ["Tech & Internet", 1, "Which company makes the PlayStation?", "Sony", "Microsoft", "Nintendo", "Sega"],
  ["Tech & Internet", 1, "Which company makes the Xbox?", "Microsoft", "Sony", "Nintendo", "Apple"],
  ["Tech & Internet", 1, "Super Mario is the star of games from which company?", "Nintendo", "Sony", "Sega", "Microsoft"],
  ["Tech & Internet", 2, "EA's FIFA video game series was renamed to what in 2023?", "EA Sports FC", "EA Football", "Ultimate Team", "eFootball"],
  ["Tech & Internet", 1, "Which company makes Fortnite?", "Epic Games", "Activision", "Rockstar Games", "Ubisoft"],
  ["Tech & Internet", 1, "Which company makes Grand Theft Auto (GTA)?", "Rockstar Games", "Epic Games", "EA", "Ubisoft"],
  ["Tech & Internet", 2, "Which company owns Minecraft?", "Microsoft", "Sony", "Nintendo", "Epic Games"],
  ["Tech & Internet", 1, "How many guesses do you get in Wordle?", "6", "5", "7", "8"],
  ["Tech & Internet", 1, "When a post spreads very fast online, we say it has gone what?", "Viral", "Trending down", "Offline", "Pinned"],
];
